version: "3.7"

services:
  prod:
    labels:
      - Author="Lucas Eliaquim"
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    volumes:
      - ./:/app
    stdin_open: true

  dev:
    labels:
      - Author="Lucas Eliaquim"
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    stdin_open: true
